import React, { useState } from 'react';
import { ShoppingCart, X, Trash2, FileDown, ChevronUp, ChevronDown, Move } from 'lucide-react';
import { useReport } from '../contexts/ReportContext';
import { Language } from '../types';
import { translations } from '../translations';
import pptxgen from 'pptxgenjs';

interface Props {
  language: Language;
}

export const ReportBuilder: React.FC<Props> = ({ language }) => {
  const { items, removeItem, moveItem } = useReport();
  const [isOpen, setIsOpen] = useState(false);
  const t = translations[language].report;

  const generatePPT = () => {
    const pres = new pptxgen();
    
    pres.title = "Market Analysis Report - HYH AI";
    pres.author = "HYH Data Analysis";

    // Title Slide
    let slide = pres.addSlide();
    slide.addText("Market Analysis Report", { x: 1, y: 2, w: '80%', fontSize: 36, bold: true, align: 'center', color: '003366' });
    slide.addText(`Generated by HYH Data Analysis on ${new Date().toLocaleDateString()}`, { x: 1, y: 4, w: '80%', fontSize: 14, align: 'center', color: '666666' });

    items.forEach((item) => {
      slide = pres.addSlide();
      slide.addText(item.title, { x: 0.5, y: 0.5, w: '90%', fontSize: 24, bold: true, color: '003366' });
      
      if (item.comment) {
        slide.addText(`Note: ${item.comment}`, { x: 0.5, y: 1, w: '90%', fontSize: 12, italic: true, color: '555555' });
      }

      if (item.type === 'chart-line') {
        const labels = item.data.map((d: any) => d.year);
        const values = item.data.map((d: any) => d.marketSize);
        slide.addChart(pres.ChartType.line, [{ name: "Market Index", labels, values }], { x: 1, y: 1.5, w: 8, h: 4.5, showLegend: true });
      } 
      else if (item.type === 'chart-bar') {
        const labels = item.data.map((d: any) => d.name);
        const values = item.data.map((d: any) => d.share);
        slide.addChart(pres.ChartType.bar, [{ name: "Market Share (%)", labels, values }], { x: 1, y: 1.5, w: 8, h: 4.5, showLegend: true, barDir: 'col' });
      }
      else if (item.type === 'swot') {
        const swot = item.data;
        slide.addText("Strengths", { x: 0.5, y: 1.5, w: 4.5, h: 0.5, fontSize: 16, bold: true, color: '008000' });
        slide.addText(swot.strengths.join("\n• "), { x: 0.5, y: 2, w: 4.5, h: 2, fontSize: 12, color: '333333', bullet: true });
        slide.addText("Weaknesses", { x: 5, y: 1.5, w: 4.5, h: 0.5, fontSize: 16, bold: true, color: 'CC0000' });
        slide.addText(swot.weaknesses.join("\n• "), { x: 5, y: 2, w: 4.5, h: 2, fontSize: 12, color: '333333', bullet: true });
        slide.addText("Opportunities", { x: 0.5, y: 4.2, w: 4.5, h: 0.5, fontSize: 16, bold: true, color: '0000CC' });
        slide.addText(swot.opportunities.join("\n• "), { x: 0.5, y: 4.7, w: 4.5, h: 2, fontSize: 12, color: '333333', bullet: true });
        slide.addText("Threats", { x: 5, y: 4.2, w: 4.5, h: 0.5, fontSize: 16, bold: true, color: 'FF9900' });
        slide.addText(swot.threats.join("\n• "), { x: 5, y: 4.7, w: 4.5, h: 2, fontSize: 12, color: '333333', bullet: true });
      }
      else if (item.type === 'text') {
          slide.addText(item.data, { x: 1, y: 1.5, w: '80%', fontSize: 14, color: '333333' });
      }
    });

    pres.writeFile({ fileName: "HYH-Report.pptx" });
  };

  return (
    <div className="fixed bottom-6 right-6 z-[9999] flex flex-col items-end">
      {isOpen && (
        <div className="bg-white rounded-xl shadow-2xl border border-slate-200 w-80 sm:w-96 mb-4 overflow-hidden flex flex-col animate-fade-in-up max-h-[500px]">
          <div className="bg-blue-600 p-4 flex justify-between items-center">
             <h3 className="text-white font-semibold flex items-center gap-2">
                <ShoppingCart className="w-5 h-5" />
                {t.builderTitle} <span className="bg-blue-500 px-2 py-0.5 rounded-full text-xs">{items.length}</span>
             </h3>
             <button onClick={() => setIsOpen(false)} className="text-white/80 hover:text-white"><X className="w-5 h-5" /></button>
          </div>
          <div className="flex-1 overflow-y-auto p-4 space-y-3 custom-scrollbar">
            {items.length === 0 && <div className="text-center text-slate-400 py-8 text-sm">{t.empty}</div>}
            {items.map((item, idx) => (
                <div key={item.id} className="bg-slate-50 p-3 rounded-lg border border-slate-100 group relative hover:border-blue-200 transition-colors">
                    <div className="flex justify-between items-start gap-2">
                        <div className="flex-1 min-w-0">
                            <span className="text-[10px] uppercase font-bold text-blue-600 bg-blue-50 px-1.5 py-0.5 rounded tracking-wider mb-1 inline-block">{t.type[item.type]}</span>
                            <h4 className="text-sm font-medium text-slate-800 line-clamp-1">{item.title}</h4>
                        </div>
                        <div className="flex items-center gap-1">
                            <div className="flex flex-col gap-0.5">
                                <button 
                                    onClick={() => moveItem(item.id, 'up')}
                                    disabled={idx === 0}
                                    className="text-slate-300 hover:text-blue-600 disabled:opacity-0 p-0.5"
                                >
                                    <ChevronUp className="w-3 h-3" />
                                </button>
                                <button 
                                    onClick={() => moveItem(item.id, 'down')}
                                    disabled={idx === items.length - 1}
                                    className="text-slate-300 hover:text-blue-600 disabled:opacity-0 p-0.5"
                                >
                                    <ChevronDown className="w-3 h-3" />
                                </button>
                            </div>
                            <button onClick={() => removeItem(item.id)} className="text-slate-400 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity p-1"><Trash2 className="w-4 h-4" /></button>
                        </div>
                    </div>
                    {item.comment && <p className="text-xs text-slate-500 mt-1 italic border-l-2 border-slate-200 pl-2 line-clamp-2">{item.comment}</p>}
                </div>
            ))}
          </div>
          <div className="p-4 border-t border-slate-100 bg-slate-50">
            <button onClick={generatePPT} disabled={items.length === 0} className="w-full bg-blue-600 text-white py-2 rounded-lg font-medium hover:bg-blue-700 transition-colors disabled:opacity-50 flex justify-center items-center gap-2"><FileDown className="w-4 h-4" />{t.generate}</button>
          </div>
        </div>
      )}
      <button 
        onClick={() => setIsOpen(!isOpen)} 
        className="bg-blue-600 text-white p-3.5 rounded-full shadow-lg hover:bg-blue-700 transition-transform hover:scale-105 flex items-center justify-center relative"
      >
        {isOpen ? <ChevronDown className="w-6 h-6" /> : <ShoppingCart className="w-6 h-6" />}
        {items.length > 0 && !isOpen && (
            <span className="absolute -top-1 -right-1 bg-red-500 text-white text-xs font-bold w-5 h-5 rounded-full flex items-center justify-center border-2 border-white">
                {items.length}
            </span>
        )}
      </button>
    </div>
  );
};